version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore
      - SERVER_PORT=9090

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
    volumes:
      - /var/lib/postgresql/data/
      - ./stats-service/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  ewm-service:
    build: ./main-service
    image: main
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STAT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore